# Generated by Django 4.2 on 2023-04-29 14:59

from django.contrib.auth.models import User
from django.db import migrations

from conf.settings import (DEFAULT_ADMIN_EMAIL, DEFAULT_ADMIN_LOGIN,
                           DEFAULT_ADMIN_PASSWORD)


def create_admin_user(apps, schema_editor):
    User.objects.create_superuser(
        username=DEFAULT_ADMIN_LOGIN,
        email=DEFAULT_ADMIN_EMAIL,
        password=DEFAULT_ADMIN_PASSWORD)

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse),
    ]
